# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Check Seclang Format

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
        with:
          go-version: "1.25.6"

      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6
        with:
          python-version: "3.14"

      - name: Clone OWASP CRS Project
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          repository: coreruleset/coreruleset
          path: crs
          ref: 8edc58f3ef4d664577e14e5132072559ff30cb34
          fetch-depth: 0
          fetch-tags: true

      - name: Check format
        run: |
          go run . -o output crs/rules/
          mkdir crs/util/crs-rules-check/rules
          go run . -s -o crs/util/crs-rules-check/rules/ output.yaml
          cd crs/util/crs-rules-check
          pip install -r requirements.txt
          ls rules
          python rules-check.py -t ../APPROVED_TAGS -r rules/*.conf
