# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Check Seclang Format

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: "1.25.0"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Clone OWASP CRS Project
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          repository: coreruleset/coreruleset
          path: crs
          ref: 8edc58f3ef4d664577e14e5132072559ff30cb34

      - name: Check format
        run: |
          go run . -o output crs/rules/
          mkdir crs/util/crs-rules-check/rules
          go run . -s -o crs/util/crs-rules-check/rules output.yaml
          cd crs/util/crs-rules-check
          pip install -r requirements.txt
          python rules-check.py -t ../APPROVED_TAGS -r rules/*.conf
